name: Build

on:
  push:

jobs:
  # -------------
  # amd64 + glibc
  # -------------
  build-linux-amd64-glibc:
    runs-on: ubuntu-latest

    outputs:
      bot-artifact: ${{ steps.upload.outputs.bot }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake git meson ninja-build tar pkg-config \
            libboost-all-dev libpq-dev zlib1g-dev

      - name: Configure project
        run: |
          cmake -G Ninja -DUSE_POSTGRES=1 -DUSE_TLS=1 -DCMAKE_BUILD_TYPE=Release -S . -B build

      - name: Build project
        run: |
          ninja -C build

      - name: Archive project
        run: |
          mkdir -p artifacts archive/singlebot archive/scriptvm

          cp -a build/singlebot/bin/. archive/singlebot/
          cp -a build/scriptvm/bin/. archive/scriptvm/

          tar -czf artifacts/singlebot-amd64-glibc.tar.gz \
            -C archive .

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-amd64-glibc
          path: artifacts/

  # -------------
  # amd64 + musl
  # -------------
  build-linux-amd64-musl:
    runs-on: ubuntu-latest

    outputs:
      bot-artifact: ${{ steps.upload.outputs.bot }}

    container:
      image: alpine/git:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          apk add --no-cache \
            build-base cmake git meson ninja tar \
            pkgconf boost-dev postgresql-dev zlib-dev

      - name: Configure project
        run: |
          cmake -G Ninja \
            -DUSE_POSTGRES=1 \
            -DUSE_TLS=1 \
            -DCMAKE_BUILD_TYPE=Release \
            -S . \
            -B build

      - name: Build project
        run: |
          ninja -C build

      - name: Archive project
        run: |
          mkdir -p artifacts archive/singlebot archive/scriptvm

          cp -a build/singlebot/bin/. archive/singlebot/
          cp -a build/scriptvm/bin/. archive/scriptvm/

          tar -czf artifacts/singlebot-amd64-musl.tar.gz \
            -C archive .

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-amd64-musl
          path: artifacts/
